version: '3.9'

services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Evently.Api
    build:
      context: .
      dockerfile: Evently.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - evently.database
    environment:
      - ConnectionStrings__DefaultConnection=Host=evently.database;Port=5432;Database=evently;Username=postgres;Password=postgres
    networks:
      - evently-network

  evently.database:
    image: postgres:17
    container_name: Evently.Database
    environment:
      POSTGRES_DB: evently
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - evently-network
    restart: unless-stopped

  evently.seq:
    image: datalust/seq:latest
    container_name: Evently.Seq
    environment:
    - ACCEPT_EULA=Y
    - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
    - 5341:5341
    - 8081:80
    networks:
      - evently-network

  evently.redis:
    image: redis:latest
    container_name: Evently.Redis
    restart: always
    ports:
    - 6379:6379
    networks:
      - evently-network


volumes:
  postgres_data:
    driver: local

networks:
  evently-network:
    driver: bridge